import type { OperationId } from "@fitia/core";
import {
  array,
  booleanSchema,
  daySummarySchema,
  entrySchema,
  foodResultSchema,
  integerSchema,
  type JsonSchema,
  mealSuggestionsSchema,
  nonnegativeNumberSchema,
  nullableMeasureSchema,
  nullableStringSchema,
  object,
  stringSchema,
  stringsSchema,
} from "./json-schema.ts";

const removedEntrySchema = {
  anyOf: [
    object({
      name: stringSchema,
      type: { const: "2" },
      eaten: booleanSchema,
      caloriesKcal: nonnegativeNumberSchema,
      proteinG: nullableMeasureSchema,
      carbsG: nullableMeasureSchema,
      fatG: nullableMeasureSchema,
      amount: nullableStringSchema,
    }),
    { type: "null" },
  ],
};

export const outputSchemas = {
  authLogin: object({
    accountId: stringSchema,
    email: nullableStringSchema,
    storage: { enum: ["macos-keychain", "windows-dpapi", "credential-store"] },
    expiresAt: nullableStringSchema,
  }),
  authLogout: object({ removed: booleanSchema }),
  authStatus: object({
    configured: booleanSchema,
    source: stringSchema,
    expiresAt: nullableStringSchema,
    expired: { type: ["boolean", "null"] },
    verified: { const: false },
  }),
  accountGet: object({
    id: stringSchema,
    email: nullableStringSchema,
    name: nullableStringSchema,
    emailVerified: booleanSchema,
    providers: stringsSchema,
  }),
  profileGet: object({
    id: stringSchema,
    email: nullableStringSchema,
    name: nullableStringSchema,
    country: nullableStringSchema,
    isPremium: booleanSchema,
    useCase: nullableStringSchema,
    goal: nullableStringSchema,
    sex: nullableStringSchema,
    creationDate: nullableStringSchema,
  }),
  premiumGet: object({ isPremium: booleanSchema }),
  foodList: object({
    scope: { const: "onboarding-preferences" },
    country: stringSchema,
    total: integerSchema,
    count: integerSchema,
    foods: array(
      object({
        id: integerSchema,
        names: object({ en: stringSchema, es: stringSchema }),
        category: stringSchema,
      }),
    ),
    limitations: stringsSchema,
  }),
  foodSearch: object({
    scope: { const: "food-database" },
    query: stringSchema,
    country: stringSchema,
    language: stringSchema,
    limit: integerSchema,
    count: integerSchema,
    foods: array(foodResultSchema),
    limitations: stringsSchema,
  }),
  mealGet: object({
    date: stringSchema,
    updateTime: stringSchema,
    consumedCaloriesKcal: nullableMeasureSchema,
    meals: array(
      object({
        id: stringSchema,
        typeId: { type: ["integer", "null"] },
        name: stringSchema,
        items: array(
          object({
            id: stringSchema,
            name: stringSchema,
            type: nullableStringSchema,
            eaten: booleanSchema,
            caloriesKcal: nullableMeasureSchema,
            proteinG: nullableMeasureSchema,
            carbsG: nullableMeasureSchema,
            fatG: nullableMeasureSchema,
            amount: nullableStringSchema,
          }),
        ),
      }),
    ),
    limitations: stringsSchema,
  }),
  daySummary: daySummarySchema,
  mealSuggest: mealSuggestionsSchema,
  mealLog: object({
    status: { enum: ["preview", "already-present", "committed"] },
    date: stringSchema,
    meal: stringSchema,
    itemId: stringSchema,
    idempotencyKey: stringSchema,
    entry: entrySchema,
    kind: { const: "quick-entry" },
    serverVerified: booleanSchema,
    mobileVerified: { const: false },
    expectedUpdateTime: stringSchema,
    fieldsChanged: stringsSchema,
  }),
  mealRefresh: object({
    status: { enum: ["preview", "already-requested", "committed"] },
    date: stringSchema,
    kind: { const: "mobile-refresh" },
    serverVerified: booleanSchema,
    mobileVerified: { const: false },
    expectedUpdateTime: stringSchema,
    fieldsChanged: stringsSchema,
  }),
  mealRemove: object({
    status: { enum: ["preview", "already-absent", "committed"] },
    date: stringSchema,
    meal: stringSchema,
    itemId: stringSchema,
    kind: { const: "remove-entry" },
    entry: removedEntrySchema,
    caloriesRemovedKcal: nonnegativeNumberSchema,
    consumedCaloriesBeforeKcal: nonnegativeNumberSchema,
    consumedCaloriesAfterKcal: nonnegativeNumberSchema,
    serverVerified: booleanSchema,
    mobileVerified: { const: false },
    expectedUpdateTime: stringSchema,
    fieldsChanged: stringsSchema,
  }),
  doctor: object({
    healthy: booleanSchema,
    checks: array(object({ name: stringSchema, status: { enum: ["pass", "fail"] }, message: stringSchema })),
  }),
} satisfies Record<OperationId, JsonSchema>;
